PAGINATED_TABLE_DATA = [
 {"Equipment": "HEX-100", "Variable": "Flow Rate", "Value": 75, "Unit": "m3/h"},
    {"Equipment": "Pump-200", "Variable": "Pressure", "Value": 120, "Unit": "bar"},
    {"Equipment": "Fuel Tank", "Variable": "Temperature", "Value": 300, "Unit": "°C"},
    {"Equipment": "Reactor-400", "Variable": "pH Level", "Value": 7.2, "Unit": "N/A"},
    {"Equipment": "Cooling Tower", "Variable": "Efficiency", "Value": 85, "Unit": "%"},
    {"Equipment": "HEX-200", "Variable": "Flow Rate", "Value": 60, "Unit": "m3/h"},
    {"Equipment": "Separator-300", "Variable": "Density", "Value": 1.05, "Unit": "kg/m3"},
    {"Equipment": "Compressor-500", "Variable": "RPM", "Value": 3500, "Unit": "RPM"},
    {"Equipment": "Boiler-600", "Variable": "Steam Output", "Value": 15, "Unit": "tons/h"},
    {"Equipment": "Chiller-700", "Variable": "Cooling Capacity", "Value": 120, "Unit": "kW"},
    {"Equipment": "HEX-150", "Variable": "Flow Rate", "Value": 85, "Unit": "m3/h"},
    {"Equipment": "Pump-300", "Variable": "Pressure", "Value": 110, "Unit": "bar"},
    {"Equipment": "Fuel Tank B", "Variable": "Temperature", "Value": 280, "Unit": "°C"},
    {"Equipment": "Separator-450", "Variable": "Viscosity", "Value": 3.5, "Unit": "Pa·s"},
    {"Equipment": "Compressor-600", "Variable": "Power Consumption", "Value": 45, "Unit": "kW"},
    {"Equipment": "Boiler-800", "Variable": "Heat Output", "Value": 22, "Unit": "MW"},
    {"Equipment": "HEX-250", "Variable": "Pressure Drop", "Value": 10, "Unit": "bar"},
    {"Equipment": "Pump-400", "Variable": "Flow Rate", "Value": 90, "Unit": "m3/h"},
    {"Equipment": "Cooling Tower B", "Variable": "Efficiency", "Value": 88, "Unit": "%"},
    {"Equipment": "Reactor-500", "Variable": "Temperature", "Value": 350, "Unit": "°C"},
    {"Equipment": "HEX-300", "Variable": "Heat Transfer", "Value": 150, "Unit": "kW"},
    {"Equipment": "Separator-600", "Variable": "Particle Size", "Value": 0.5, "Unit": "mm"},
    {"Equipment": "Compressor-700", "Variable": "RPM", "Value": 4000, "Unit": "RPM"},
    {"Equipment": "Fuel Tank C", "Variable": "Volume", "Value": 5000, "Unit": "liters"},
    {"Equipment": "Boiler-900", "Variable": "Steam Pressure", "Value": 18, "Unit": "bar"},
    {"Equipment": "Chiller-800", "Variable": "Cooling Capacity", "Value": 140, "Unit": "kW"},
    {"Equipment": "Reactor-600", "Variable": "pH Level", "Value": 6.8, "Unit": "N/A"},
    {"Equipment": "Pump-500", "Variable": "Pressure", "Value": 125, "Unit": "bar"},
    {"Equipment": "Separator-700", "Variable": "Density", "Value": 1.08, "Unit": "kg/m3"},
    {"Equipment": "Cooling Tower C", "Variable": "Water Flow", "Value": 1000, "Unit": "m3/h"},
]

INITIAL_NODES_DATA = [    {"Name": "HEX-100", "Type": "type1"},
    {"Name": "Pump-200", "Type": "type1"},
    {"Name": "Fuel Tank", "Type": "type2"},
    {"Name": "Air Intake", "Type": "type2"},
    {"Name": "Reactor-400", "Type": "type1"},
    {"Name": "Cooling Tower", "Type": "type3"},
    {"Name": "Separator-500", "Type": "type1"}]

INITIAL_EDGES_DATA = [{"Upstream Node": "Air Intake", "Downstream Node": "Fuel Tank"},
    {"Upstream Node": "Fuel Tank", "Downstream Node": "Pump-200"},
    {"Upstream Node": "Pump-200", "Downstream Node": "Reactor-400"},
    {"Upstream Node": "HEX-100", "Downstream Node": "Reactor-400"},
    {"Upstream Node": "Reactor-400", "Downstream Node": "Separator-500"},
    {"Upstream Node": "Separator-500", "Downstream Node": "Cooling Tower"}]